-- Generated by Oracle SQL Developer Data Modeler 3.3.0.747
--   at:        2013-11-03 22:54:49 BRST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g




CREATE TABLE CLIENTE
  (
    COD_MATRIZ  INTEGER NOT NULL ,
    NOME_MATRIZ VARCHAR2 (70) ,
    COD_FILIAL  INTEGER NOT NULL ,
    NOME_FILIAL VARCHAR2 (70)
  ) ;
ALTER TABLE CLIENTE ADD CONSTRAINT CLIENTE_PK PRIMARY KEY
(
  COD_MATRIZ, COD_FILIAL
)
;

CREATE TABLE FATURAMENTO
  (
    NF   INTEGER NOT NULL ,
    DATA DATE ,
    VLR_TOTAL FLOAT ,
    IMPOSTO FLOAT ,
    TX_IMP FLOAT ,
    COD_MATRIZ INTEGER NOT NULL ,
    COD_FILIAL INTEGER NOT NULL
  ) ;
ALTER TABLE FATURAMENTO ADD CONSTRAINT FATURAMENTO_PK PRIMARY KEY
(
  NF
)
;

CREATE TABLE PEDIDO
  (
    COD_PEDIDO   INTEGER NOT NULL ,
    COD_SOFTWARE INTEGER NOT NULL ,
    COD_FABRICA  INTEGER NOT NULL ,
    QTDE         INTEGER ,
    NF           INTEGER NOT NULL ,
    VLR_UNITARIO FLOAT
  ) ;
ALTER TABLE PEDIDO ADD CONSTRAINT PEDIDO_PK PRIMARY KEY
(
  COD_PEDIDO, COD_SOFTWARE
)
;

CREATE TABLE SOFTWARE
  (
    COD_SOFTWARE  INTEGER NOT NULL ,
    NOME_SOFTWARE VARCHAR2 (70) ,
    COD_FABRICA   INTEGER NOT NULL ,
    NOME_FABRICA  VARCHAR2 (70)
  ) ;
ALTER TABLE SOFTWARE ADD CONSTRAINT SOFTWARE_PK PRIMARY KEY
(
  COD_SOFTWARE, COD_FABRICA
)
;

ALTER TABLE FATURAMENTO ADD CONSTRAINT FATURAMENTO_CLIENTE_FK FOREIGN KEY ( COD_MATRIZ, COD_FILIAL ) REFERENCES CLIENTE ( COD_MATRIZ, COD_FILIAL ) ;

ALTER TABLE PEDIDO ADD CONSTRAINT PEDIDO_FATURAMENTO_FK FOREIGN KEY ( NF ) REFERENCES FATURAMENTO ( NF ) ;

ALTER TABLE PEDIDO ADD CONSTRAINT PEDIDO_SOFTWARE_FK FOREIGN KEY ( COD_SOFTWARE, COD_FABRICA ) REFERENCES SOFTWARE ( COD_SOFTWARE, COD_FABRICA ) ;


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             4
-- CREATE INDEX                             0
-- ALTER TABLE                              7
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
